### ISSUE TITLE
Qtestsuite hydro fixes

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki_desktop#9]
- Add some documentation to the [wiki](http://ros.org/wiki/kobuki_qtestsuite)
- Fix some bugs in plotting due to changes in rqt:

```
Traceback (most recent call last):
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rqt_plot/plot_widget.py", line 168, in update_plot
    self.data_plot.redraw()
  File "/opt/turtlebot/kobuki_desktop/kobuki_qtestsuite/plugins/../src/kobuki_qtestsuite/full_size_data_plot.py", line 54, in redraw
    data_x, data_y, plot = curve
ValueError: too many values to unpack
```

**Comment by stonier** [comment]
Also fix the [battery tutorial](http://www.ros.org/wiki/kobuki/Tutorials/Testing%20Batteries) to use this instead of scripts.

https://github.com/yujinrobot/kobuki/issues/197

**Comment by stonier** [comment]
The [roswiki](http://ros.org/wiki/kobuki_qtestsuite) page updated.

**Comment by stonier** [comment]
The [battery tutorial](http://ros.org/wiki/kobuki/Tutorials/Testing%20Batteries) also updated.
